### ISSUE TITLE
Issue with bayesGARCH

### ISSUE THREAD

**Issue by rhozon** [ArdiaD/bayesGARCH#1]
Hi, I´m trying to run the following script 

library(tidyr)
library(dplyr)
library(bayesGARCH)
library(coda)
library(ggplot2)
library(patchwork)
library(quantmod)

CORN_futures <- getSymbols("ZC=F", auto.assign = FALSE,
                    from = "2021-08-01", end = Sys.Date()) # Target

log_ret <- diff(log(Cl(CORN_futures)))

log_ret <- log_ret[1:182,] %>% na.exclude()

sum(is.na(log_ret))

log_ret <- log_ret[2:180]

set.seed(1234)

MCMC <- bayesGARCH(log_ret, control = list(l.chain = 5000, n.chain = 2))

Error in uniroot(fn.neg.alpha, interval = c(alpha.min, alpha.max), tol = .Machine$double.eps, : f() values at end points not of 
opposite sign Calls: <Anonymous> ... bayesGARCH -> fn.bayesGARCH -> fn.block -> fn.nu.full -> unitroot

How can I fix it ?

**Comment by ArdiaD** [comment]
log_ret <- 100 * as.vector(log_ret)
set.seed(1234)
MCMC <- bayesGARCH(log_ret, control = list(l.chain = 5000, n.chain = 2))

Btw, time series is very short for GARCH models. At least 500-750 observations are required

**Comment by rhozon** [comment]
Thanks a lot David!! Your contribution to bayesian econometrics is amazing!

**Comment by ArdiaD** [comment]
@rhozon happy to help! thx for the kind words
